### ISSUE TITLE
blank white screen (cordova deviceready not firing)

### ISSUE THREAD

**Issue by syahman** [telerik/whatsername#1]
hi,
i'm trying to add kendo mobile application  into deviceready event to add device functionality, 

```javascript
document.addEventListener('deviceready', function () {
dt.app = new kendo.mobile.Application(document.body, { //document.body is default, but I'm being explicit
    skin: 'flat',
    initial: 'dashboardView', // splash screen and apps information
    init: function() {
        //fix mouse events in iOS don't do it for android, causes more issues than it fixes
         
        kendo.UserEvents.defaultThreshold(kendo.support.mobileOS.device === 'android' ? 0:20);
        
    }
});
},false);
```

it only shows blank white screen and no error in console.

cordova 5.2, osx , android 4.4.4

**Comment by syahman** [comment]
refer to CSP.

**Comment by codylindley** [comment]
CSP?

**Comment by syahman** [comment]
Content Security Policy. i think its related with  latest cordova whitelist plugin. I'm developing an apps that have iframe to external url  and connection to google chart / google spreadsheet api. 

btw, thanks for your opiniated guide :-)

**Comment by codylindley** [comment]
Ah. Gotcha. 

Your welcome glad it is useful.
